version: "3.5"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: megadolls.pgadmin@getnada.com
      PGADMIN_DEFAULT_PASSWORD: Megadolls2022
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks: 
      - webnet
    
  django_wsgi:
    container_name: django_wsgi
    build: .
    env_file:
      - .env
    command: uwsgi --socket=:9000 --module=megadolls.wsgi:application --py-autoreload=1
    volumes:
      - .:/code
    networks: 
      - webnet
  
  nginx:
    image: nginx:1.15.0
    depends_on:
      - django_wsgi
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # - ./nginx/privkey.pem:/etc/letsencrypt/live/megadolls.com/privkey.pem:ro
      # - ./nginx/fullchain.pem:/etc/letsencrypt/live/megadolls.com/fullchain.pem:ro
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    networks:
      - webnet
    ports:
      - "80:80"
      - 443:443

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks: 
  webnet:

volumes:
  pgadmin: {}
  