# Generated by Django 4.1.4 on 2022-12-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sloperuserdesign',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sloperuserfolder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='sloperuserdesign',
            name='file_path',
        ),
        migrations.AddField(
            model_name='sloperuserdesign',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sloperuserdesign',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sloperuserdesign',
            name='folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.sloperuserfolder'),
        ),
    ]
